### ISSUE TITLE
JsonNull

### ISSUE THREAD

**Issue by Neoshka73** [InventivetalentDev/CustomSkins#11]
Problem with loading the skin:
`>createcustomskin default http://mc.hypercradle.ru/default.png
[17:56:37 INFO]: Uploading skin...
[17:56:38 INFO]: JsonNull
[17:56:38 WARN]: Exception in thread "pool-39-thread-2"
[17:56:38 WARN]: java.lang.RuntimeException: java.lang.UnsupportedOperationException: JsonNull
[17:56:38 WARN]:        at org.inventivetalent.skullclient.SkullClient$1.run(SkullClient.java:87)
[17:56:38 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:56:38 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[17:56:38 WARN]:        at java.lang.Thread.run(Thread.java:748)
[17:56:38 WARN]: Caused by: java.lang.UnsupportedOperationException: JsonNull
[17:56:38 WARN]:        at com.google.gson.JsonElement.getAsInt(JsonElement.java:243)
[17:56:38 WARN]:        at org.inventivetalent.skullclient.SkullClient$1.run(SkullClient.java:79)
[17:56:38 WARN]:        ... 3 more`
What to do?

**Comment by Neoshka73** [comment]
`>version
[18:03:43 INFO]: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[18:03:43 INFO]: Checking version, please wait...
[18:03:44 INFO]: You are 852 version(s) behind
`
`>version CustomSkins
[18:03:53 INFO]: CustomSkins version 1.4.1-SNAPSHOT
[18:03:53 INFO]: Author: inventivetalent`
