### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by TomberWolf** [InventivetalentDev/CustomSkins#2]
On Thermos 1.7.10 we get this error:

`[00:02:47] [Protocol Worker #1 - CustomSkins - [recv: , send: S38PacketPlayerListItem[56, legacy: 201]]/ERROR]: [CustomSkins] Unhandled exception occured in onAsyncPacket() for CustomSkins
java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getPlayerInfoDataLists()Lcom/comphenix/protocol/reflect/StructureModifier;
	at de.janmm14.customskins.shadedlibs.com.comphenix.packetwrapper.WrapperPlayServerPlayerInfo.getData(WrapperPlayServerPlayerInfo.java:49) ~[custom-skins-bootstrap-1.3-SNAPSHOT-75.jar:?]
	at de.janmm14.customskins.bukkit.ProtocolLibSkinHandler.onPacketSending(ProtocolLibSkinHandler.java:78) ~[custom-skins-bootstrap-1.3-SNAPSHOT-75.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:641) [custom-skins-ProtocolLib-3.7.0.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:597) [custom-skins-ProtocolLib-3.7.0.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:49) [custom-skins-ProtocolLib-3.7.0.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) [custom-skins-ProtocolLib-3.7.0.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) [custom-skins-ProtocolLib-3.7.0.jar:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [CraftTask.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [CraftAsyncTask.class:1.7.10-1614.58]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
`

**Comment by TomberWolf** [comment]
Wrong Plugin... sorry! It was so similar.
