### ISSUE TITLE
1.12 /applycustomskin bug

### ISSUE THREAD

**Issue by Ezzcargot** [InventivetalentDev/CustomSkins#9]
Hi Inventive Talent :D when I type /applycustomskin in 1.12, there is a error message with all the registered skins:
Unhandled exception, see console for details: Unhandled exception while invoking command method in CustomSkinsv1.4.1-SNAPSHOT#applySkin
An internal error occured while attempting to perform this command

Thank you soooo much 
Nathan

**Comment by Ezzcargot** [comment]
This is the console error:
`[17:39:55] [Server thread/INFO]: Ezzcargot issued server command: /applycustomskin test[17:39:55] [Server thread/ERROR]: nullorg.bukkit.command.CommandException: Unhandled exception executing 'applycustomskin test' in org.inventivetalent.pluginannotations.command.AnnotatedCommand$BukkitCommand(applycustomskin)at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]Caused by: org.inventivetalent.pluginannotations.command.exception.UnhandledCommandException: Unhandled exception while invoking command method in CustomSkins v1.4.1-SNAPSHOT#applySkinat org.inventivetalent.pluginannotations.command.AnnotatedCommand.onCommand(AnnotatedCommand.java:165) ~[?:?]at org.inventivetalent.pluginannotations.command.AnnotatedCommand$BukkitCommand.execute(AnnotatedCommand.java:401) ~[?:?]at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]... 14 moreCaused by: java.lang.NoClassDefFoundError: org/inventivetalent/packetlistener/handler/PacketHandlerat org.inventivetalent.customskins.CustomSkins.applySkin(CustomSkins.java:207) ~[?:?]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]at org.inventivetalent.pluginannotations.command.AnnotatedCommand.onCommand(AnnotatedCommand.java:161) ~[?:?]at org.inventivetalent.pluginannotations.command.AnnotatedCommand$BukkitCommand.execute(AnnotatedCommand.java:401) ~[?:?]at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]... 14 moreCaused by: java.lang.ClassNotFoundException: org.inventivetalent.packetlistener.handler.PacketHandlerat java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_141]at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]at org.inventivetalent.customskins.CustomSkins.applySkin(CustomSkins.java:207) ~[?:?]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]at org.inventivetalent.pluginannotations.command.AnnotatedCommand.onCommand(AnnotatedCommand.java:161) ~[?:?]at org.inventivetalent.pluginannotations.command.AnnotatedCommand$BukkitCommand.execute(AnnotatedCommand.java:401) ~[?:?]at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]... 14 more`

**Comment by Ezzcargot** [comment]
Sorry it was just cause I don't downloaded PacketListenerAPI
Thank you
